services:
  - type: web
    name: clauseguard-web
    runtime: docker
    repo: https://github.com/Timmydavid123/clauseguard
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: AI_API_KEY
        sync: false
      - key: ANTHROPIC_MODEL
        value: claude-3-haiku-20240307
      - key: REDIS_URL
        fromService:
          type: redis
          name: clauseguard-redis
          property: connectionString
      - key: RENDER
        value: true
      - key: PORT
        value: 10000

  - type: redis
    name: clauseguard-redis
    ipAllowList: []
    plan: free

  - type: worker
    name: clauseguard-worker
    runtime: docker
    repo: https://github.com/Timmydavid123/clauseguard
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    command: celery -A clauseguard worker --loglevel=info
    envVars:
      - key: AI_API_KEY
        sync: false
      - key: ANTHROPIC_MODEL
        value: claude-3-haiku-20240307
      - key: REDIS_URL
        fromService:
          type: redis
          name: clauseguard-redis
          property: connectionString
      - key: RENDER_WORKER
        value: true